version: "3"
services:
    db:
        image: mariadb:10.3
        container_name: db
        environment:
            - MYSQL_ROOT_PASSWORD=patternMysqlPassword
            - TZ=Europe/Moscow
        volumes:
            - /home/webmaster/pattern/mysql_data:/var/lib/mysql
            - /home/webmaster/pattern/mysql_conf.d:/var/lib/mysql/conf.d
        ports:
            - "3306:3306"
        restart: always
    back-end:
        image: node:14.16.1
        container_name: back-end
        command: node bin/www
        environment:
            - TZ=Europe/Moscow
        ports:
            - "3000:3000"
        volumes:
            - /home/webmaster/pattern:/home/webmaster/pattern       
        restart: always
        links:
            - db
        working_dir: /home/webmaster/pattern